### ISSUE TITLE
Why Tailwind CSS 4.0?

### ISSUE THREAD

**Issue by victorlucss** [nikolailehbrink/retail#1]
Currently, the new version of Tailwind is still in development, therefore using an alpha version could bring a lot of incompatibilities with libraries that still don't rely on the non-stable version. In the [Adam's post](https://tailwindcss.com/blog/tailwindcss-v4-alpha) it's encouraged to use it in the projects, but since this is a template I would forsake a version that it's still in progress.

My suggestion would be to move back to the latest stable version ([3.4.14](https://www.npmjs.com/package/tailwindcss/v/3.4.14)) and have another branch on the template to be prepared for when the v4 comes. Otherwise, other tools to assist fast-paced or easy from-the-get-go project template would not properly work with the current situation (aka Shadcn, although it has [an open discussion](https://github.com/tailwindlabs/tailwindcss/discussions/13211)).

Besides that, I love your initiative and will try to collaborate with a PR on this idea any time soon.

**Comment by nikolailehbrink** [comment]
Hi @victorlucss,

You're absolutely right! I originally used Tailwind v3.4 but left v4 in the project, hoping it would attract more people interested in trying out the latest version. However, I agree it’s not ideal for production sites yet. I’m currently on vacation, but I’ll downgrade to v3.4 when I’m back and will update this thread once it’s done.

Thanks for the feedback!

**Comment by victorlucss** [comment]
Hi @nikolailehbrink, #2 is up. 

I reverted your changes and 'upgraded' the version to 3.4.14 in the referenced PR. Hopefully you will be able to push it forward to Tailwind CSS 4 when the time comes, looking forward for it! :)

**Comment by nikolailehbrink** [comment]
THank you very much for the PR. Made a small change to the README, but other than that everything was fine! 😊
